CREATE DATABASE IF NOT EXISTS aula_02; -- CRIAR O BANCO DE DADOS "AULA 02"
-- DROP DATABASE IF EXISTS aula_02; -- EXCLUIR O BANCO DE DADOS "AULA 02"
USE aula_02; -- USE O BANCO "AULA 02"
-- DROP TABLE clientes; -- EXCLUA A TABELA "clientes"

CREATE TABLE IF NOT EXISTS clientes (
 id_cliente INT AUTO_INCREMENT NOT NULL,
 data_nasc DATE NOT NULL,
 cep CHAR(8),
 email VARCHAR(80) NOT NULL UNIQUE,
 cidade VARCHAR(50) DEFAULT 'Brasilia',
 rua VARCHAR(50) DEFAULT '1º Bota',
 idade INT NOT NULL CHECK (idade >= 18),
 PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS telefones (
 id_telefone INT AUTO_INCREMENT NOT NULL,
 numero VARCHAR(15) NOT NULL UNIQUE,
 id_cliente INT,
 PRIMARY KEY (id_telefone),
 FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
);


ALTER TABLE telefones ADD ddd CHAR(2);
-- ALTER TABLE telefones DROP COLUMN ddd; SERIA UM DROP PARA UMA COLUNA ESPECIFICA
ALTER TABLE telefones CHANGE COLUMN numero telefone VARCHAR(15);
